# Generated by Django 6.0.5 on 2026-05-21 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='reserved_accommodations', to=settings.AUTH_USER_MODEL, verbose_name='رزرو شده توسط'),
        ),
    ]
