# Generated by Django 6.0.5 on 2026-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('destination', models.CharField(max_length=200, verbose_name='مقصد')),
                ('duration', models.CharField(choices=[('1day', 'یک روزه'), ('2day', 'دو روزه'), ('3day', 'سه روزه'), ('week', 'یک هفته')], max_length=20, verbose_name='مدت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تور',
                'verbose_name_plural': 'تورها',
                'ordering': ['start_date'],
            },
        ),
    ]
