# Generated by Django 6.0.5 on 2026-05-20 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='reserved_tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
