# Generated by Django 6.0.5 on 2026-06-26 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_reserved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded_services',
            field=models.TextField(blank=True, verbose_name='خدمات شامل نشده'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_services',
            field=models.TextField(blank=True, verbose_name='خدمات شامل شده'),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(blank=True, verbose_name='برنامه سفر'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='reserved_tours', to=settings.AUTH_USER_MODEL, verbose_name='رزرو شده توسط'),
        ),
    ]
